#!/usr/local/bin/perl -w

use strict;
use FindBin;
use lib "$FindBin::Bin/../lib/perl";

use XML::Writer;
use ProteomeXchange::Dataset;
use ProteomeXchange::DatasetParser;
use ProteomeXchange::ShowDataset;
use ProteomeXchange::DDIJS;
use LWP::UserAgent;
use HTTP::Request;


my $ua = LWP::UserAgent->new();

$| = 1;
use CGI qw/:standard/;
my $cgi = new CGI;
$cgi->charset('utf-8');

our $CGI_BASE_DIR = $cgi->new->url();
$CGI_BASE_DIR =~ s/cgi.*/cgi/;

my $response = {};
$response->{result} = "ERROR";
$response->{message} = "ERROR: Unhandled exception E001";
my @tmp = ( 'Dataset service start' );
$response->{info} = \@tmp;

my $ddi_js = ProteomeXchange::DDIJS->new();

my $params;

my @parameters = qw ( test verbose action ID filterstr outputMode detailLevel );

our @template;


#### Extract CGI parameters
foreach my $parameter ( @parameters ) {
  if ($cgi->param($parameter)) {
    $params->{$parameter} = $cgi->param($parameter);
  	push(@{$response->{info}},"Found input parameter $parameter=$params->{$parameter}") if ($cgi->param('verbose'));
  }
}

my $skinLink = 'http://proteomecentral.proteomexchange.org/template.php';
$response = $ua->request( HTTP::Request->new( GET => "$skinLink" ) );
if ( $response -> is_success()){
  @template = split( "\n", $response->content() );
}else{
  $response->{message} = "unable to open template http://proteomecentral.proteomexchange.org/template.php\n";
  exit;
}

#### Also extract command-line parameters, useful for testing
foreach my $arg ( @ARGV ) {
  if ( $arg =~ /(\S+)=(\S+)/) {
    my $key = $1;
	  my $value = $2;
		foreach my $parameter ( @parameters ) {
			if ($key eq $parameter) {
				$params->{$parameter} = $value;
				push(@{$response->{info}},"Found input parameter $key=$value");
			}
		}
  }# else {
   #  $response->{message} = "ERROR: Unable to parse method line parameter '$arg'\n";
	 #  exit;
  #}
}

$response->{verbose} = $params->{verbose};
my $outputMode = $params->{outputMode} || 'html';

my $HTML  = new ProteomeXchange::ShowDataset;
#### Handle a dataset identifier

if ($params->{action} && $params->{action} =~ /search/i){
  if ($params->{ID}  && $params->{ID} ne '') {
    $HTML -> showDataset(params=>$params,response=>$response);
  }else{
    $HTML -> listDatasets(params=>$params,response=>$response);
  }
} else {
  if ($params->{ID} && $params->{ID} ne '') {
    if ($outputMode =~ /html/i){
      $HTML -> printPageHeader (template => \@template);
      $HTML -> showDataset(params=>$params,response=>$response);
      $HTML -> printPageFooter (template => \@template);
    }else{
      $HTML -> showDataset(params=>$params,response=>$response);
    }
  } else {
    if ($outputMode =~ /html/i){
      #$HTML -> printPageHeader (template => \@template);
      my $js = get_js();
      $HTML -> printTablePageHeader (template => \@template, inject_content => $js);
      $HTML -> listDatasets(params=>$params,response=>$response);
      $HTML -> printPageFooter (template => \@template);
    } else {
      $HTML -> listDatasets(params=>$params,response=>$response);
    }
  }
}


#####################################################################
# get_js                                                            #
#####################################################################
sub get_js {

  my $js = $ddi_js->get_js_includes(1);
  $js .= qq~
  <script type="text/javascript">

  function plot_onclick( search_key ) {
    document.getElementById("field").value = search_key;
    myQueryEvent();
  }
  </script>
<div style="margin: auto; text-align: center">
 <div style="display: inline-block; text-align: center">
    <div class="col-md-4">
      <div class="panel panel-default" style="width:300px; height:300px" id='species_chart'><B><center>Top 10 Species</center></B></div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default" style="width:300px; height:300px" id='keywords'></div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default" style="width:300px; height:300px" id='instrument_chart'><B><center>Top 10 Instruments</center></B></div>
    </div>
 </div>
</div>
  ~;
  $js .= $ddi_js->get_onload_script();
  return $js;
}


exit;
