#!/usr/local/bin/perl -w

use strict;
use FindBin;
use lib "$FindBin::Bin/../lib/perl";

use XML::Writer;
use ProteomeXchange::Dataset;
use ProteomeXchange::DatasetParser;
use ProteomeXchange::ShowDataset;
use LWP::UserAgent;
use HTTP::Request;
my $ua = LWP::UserAgent->new();

$| = 1;
use CGI qw/:standard/;
my $cgi = new CGI;
$cgi->charset('utf-8');

our $CGI_BASE_DIR = $cgi->new->url();
$CGI_BASE_DIR =~ s/cgi.*/cgi/;

my $response = {};
$response->{result} = "ERROR";
$response->{message} = "ERROR: Unhandled exception E001";
my @tmp = ( 'Dataset service start' );
$response->{info} = \@tmp;

my $params;

my @parameters = qw ( test verbose action ID filterstr outputMode detailLevel );
 
our @template;


#### Extract CGI parameters
foreach my $parameter ( @parameters ) {
  if ($cgi->param($parameter)) {
    $params->{$parameter} = $cgi->param($parameter);
  	push(@{$response->{info}},"Found input parameter $parameter=$params->{$parameter}") if ($cgi->param('verbose'));
  }
}

my $skinLink = 'http://proteomecentral.proteomexchange.org/template.php';
$response = $ua->request( HTTP::Request->new( GET => "$skinLink" ) );
if ( $response -> is_success()){
  @template = split( "\n", $response->content() );
}else{
  $response->{message} = "unable to open template http://proteomecentral.proteomexchange.org/template.php\n";
  exit;
}

#### Also extract command-line parameters, useful for testing
foreach my $arg ( @ARGV ) {
  if ( $arg =~ /(\S+)=(\S+)/) {
    my $key = $1;
	  my $value = $2;
		foreach my $parameter ( @parameters ) {
			if ($key eq $parameter) {
				$params->{$parameter} = $value;
				push(@{$response->{info}},"Found input parameter $key=$value");
			}
		}
  }# else {
   #  $response->{message} = "ERROR: Unable to parse method line parameter '$arg'\n";
	 #  exit;
  #}
}

$response->{verbose} = $params->{verbose};
my $outputMode = $params->{outputMode} || 'html'; 
 
my $HTML  = new ProteomeXchange::ShowDataset;
#### Handle a dataset identifier

if ($params->{action} && $params->{action} =~ /search/i){
	if ($params->{ID}  && $params->{ID} ne '') {
		$HTML -> showDataset(params=>$params,response=>$response);
	}else{
		$HTML -> listDatasets(params=>$params,response=>$response);
	}
}else{
	if ($params->{ID} && $params->{ID} ne '') {
    if ($outputMode =~ /html/i){
			$HTML -> printPageHeader (template => \@template);
			$HTML -> showDataset(params=>$params,response=>$response);
			$HTML -> printPageFooter (template => \@template);
    }else{
       $HTML -> showDataset(params=>$params,response=>$response);
    }
	}else{
    if ($outputMode =~ /html/i){
			$HTML -> printTablePageHeader (template => \@template);
			$HTML -> listDatasets(params=>$params,response=>$response);
			$HTML -> printPageFooter (template => \@template);
    }else{
      $HTML -> listDatasets(params=>$params,response=>$response);
    }
  }
}

exit;
