# coding: utf-8

"""
    Proteomics Expression Interface

    [Proteomics eXpression Interface](https://github.com/HUPO-PSI/proxi-schemas/)

    OpenAPI spec version: 0.1.1
    Contact: yperez@ebi.ac.uk
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class ProteinIdentification(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, protein_accession=None, start_position=None, end_position=None):
        """
        ProteinIdentification - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'protein_accession': 'str',
            'start_position': 'int',
            'end_position': 'int'
        }

        self.attribute_map = {
            'protein_accession': 'proteinAccession',
            'start_position': 'startPosition',
            'end_position': 'endPosition'
        }

        self._protein_accession = protein_accession
        self._start_position = start_position
        self._end_position = end_position

    @property
    def protein_accession(self):
        """
        Gets the protein_accession of this ProteinIdentification.
        Protein accession identified

        :return: The protein_accession of this ProteinIdentification.
        :rtype: str
        """
        return self._protein_accession

    @protein_accession.setter
    def protein_accession(self, protein_accession):
        """
        Sets the protein_accession of this ProteinIdentification.
        Protein accession identified

        :param protein_accession: The protein_accession of this ProteinIdentification.
        :type: str
        """

        self._protein_accession = protein_accession

    @property
    def start_position(self):
        """
        Gets the start_position of this ProteinIdentification.
        Start position

        :return: The start_position of this ProteinIdentification.
        :rtype: int
        """
        return self._start_position

    @start_position.setter
    def start_position(self, start_position):
        """
        Sets the start_position of this ProteinIdentification.
        Start position

        :param start_position: The start_position of this ProteinIdentification.
        :type: int
        """

        self._start_position = start_position

    @property
    def end_position(self):
        """
        Gets the end_position of this ProteinIdentification.
        End position

        :return: The end_position of this ProteinIdentification.
        :rtype: int
        """
        return self._end_position

    @end_position.setter
    def end_position(self, end_position):
        """
        Sets the end_position of this ProteinIdentification.
        End position

        :param end_position: The end_position of this ProteinIdentification.
        :type: int
        """

        self._end_position = end_position

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
